import type { Metadata } from "next";
export const metadata:Metadata={title:"Privacy Policy",description:"How Scrap Finance Partners handles enquiry data."};
const sections=[
["Who we are","Scrap Finance Partners provides commercial finance consultancy to UK scrap metal, waste and recycling businesses."],
["What we collect","When you submit an enquiry, we collect the details you provide: name, company, email, optional phone number, selected business challenge and any written context. We also attach the current page, referring domain and campaign parameters to help route and understand the enquiry."],
["Why we collect it","We use this information to respond to a business enquiry you initiated and, if you become a client, to deliver the agreed work. The relevant lawful bases are legitimate interests and contract."],
["Where it goes","Form submissions are saved in the secure client workspace and may trigger a notification through Resend to the configured business mailbox. Aggregate website analytics and campaign parameters are used to understand site usage and enquiry sources. We do not sell or rent enquiry details."],
["How long we keep it","Enquiries that do not progress are deleted within 12 months. Client records are kept for the engagement and any period required by UK law."],
["Your rights","Under UK GDPR you may ask what information is held about you, request a correction or request deletion where applicable. You may also complain to the Information Commissioner’s Office."]
];
export default function PrivacyPage(){return <><section className="editorial-shell border-b-2 border-black p-6 sm:p-10 lg:p-12"><p className="editorial-label">Data handling / Updated 29 July 2026</p><h1 className="mt-10">Privacy policy</h1></section><section className="editorial-shell border-b-2 border-black">{sections.map(([title,copy])=><article key={title} className="grid grid-cols-1 border-b border-black last:border-b-0 md:grid-cols-12"><h2 className="p-5 text-2xl md:col-span-3 md:border-r md:border-black md:p-7">{title}</h2><p className="border-t border-black p-5 text-ink-secondary md:col-span-9 md:border-t-0 md:p-7">{copy}</p></article>)}</section></>}