import type { Metadata } from "next"; import Link from "next/link";
export const metadata: Metadata = { title: "Services", description: "Commercial finance support for UK scrap and recycling businesses." };
const rows=[
["Diagnose","Finance Health Check","Test the commercial picture across margin, stock, transport, cash and reporting. Establish what deserves attention before a larger scope is discussed.","A prioritised action view"],
["Improve","Scoped improvement work","Address a defined issue uncovered through diagnosis—without turning every finding into a programme.","A bounded piece of work"],
["Control","Ongoing commercial finance support","Provide regular analysis, decision support and follow-through where the business needs continuing commercial discipline.","A consistent decision rhythm"]
];
export default function Services(){return <>
<section className="editorial-shell grid grid-cols-1 border-b-2 border-black lg:grid-cols-12"><div className="border-b-2 border-black p-6 sm:p-10 lg:col-span-8 lg:border-b-0 lg:border-r-2 lg:p-12"><h1 className="seq seq-1">Start with the commercial decision—not a catalogue of deliverables.</h1><p className="seq seq-2 editorial-intro mt-8">Three ways the work runs, what each one examines, and what you are left holding at the end of it.</p></div><div className="flex items-end bg-copper p-6 sm:p-10 lg:col-span-4"><p className="font-serif text-3xl font-bold leading-tight">Diagnose first. Scope only what earns its place.</p></div></section>
<section className="editorial-shell border-b-2 border-black"><div className="editorial-index">{rows.map(([stage,title,copy,outcome])=><article key={stage} className="grid grid-cols-1 md:grid-cols-12"><div className="border-b border-black p-5 md:col-span-2 md:border-b-0 md:border-r md:p-7"><p className="editorial-label text-copper-dim">{stage}</p></div><h2 className="border-b border-black p-5 text-3xl md:col-span-3 md:border-b-0 md:border-r md:p-7">{title}</h2><p className="border-b border-black p-5 text-ink-secondary md:col-span-5 md:border-b-0 md:border-r md:p-7">{copy}</p><p className="p-5 font-semibold md:col-span-2 md:p-7">{outcome}</p></article>)}</div></section>
<section className="editorial-shell grid grid-cols-1 bg-graphite text-white lg:grid-cols-12"><div className="border-b border-[#4d534e] p-6 sm:p-9 lg:col-span-8 lg:border-b-0 lg:border-r"><h2 className="text-white">The Health Check is the clearest first step.</h2></div><Link href="/health-check" className="flex min-h-32 items-center justify-between bg-copper p-6 text-lg font-bold text-graphite hover:bg-[#f0f0ed] sm:p-9 lg:col-span-4">Examine the scope <span aria-hidden>→</span></Link></section>
</>}