import type { Metadata } from "next";
import Link from "next/link";
import LeadForm from "@/components/lead-form";

export const metadata: Metadata = { title: "Finance Health Check", description: "A focused commercial finance review for UK scrap and recycling businesses." };
const areas = ["Trading margin and deal economics", "Stock records and reconciliation", "Haulage and transport capacity", "Yard labour and operational involvement", "Working capital and cash visibility", "Management reporting and decision rhythm"];
export default function HealthCheckPage(){return <>
<section className="border-b border-hairline bg-grid"><div className="mx-auto grid w-full max-w-7xl min-w-0 grid-cols-1 gap-10 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-2"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.16em] text-copper">Finance Health Check</p><h1 className="mt-4 text-ink">Find the commercial questions worth fixing first.</h1><p className="mt-6 max-w-xl text-lg text-ink-secondary">A focused review of the numbers, processes and operational demands behind margin, stock, transport and cash decisions.</p><Link href="#request" className="mt-8 inline-flex min-h-12 items-center justify-center bg-copper px-6 font-semibold text-white">Request a Health Check</Link></div><div className="min-w-0 border-l-4 border-copper bg-navy p-6 sm:p-8"><p className="font-serif text-2xl font-bold text-white">Designed for owner-managed scrap and recycling businesses that need a clearer commercial picture.</p><p className="mt-4 text-sm text-ink-secondary">Scope, timing and fee are confirmed before work begins. No savings or return is guaranteed.</p></div></div></section>
<section id="what-we-review" className="border-b border-hairline bg-panel"><div className="mx-auto w-full max-w-7xl px-4 py-16 sm:px-6"><h2>What the review can cover</h2><div className="mt-8 grid min-w-0 grid-cols-1 border-l border-t border-hairline md:grid-cols-2 lg:grid-cols-3">{areas.map((area,i)=><article key={area} className="min-w-0 border-b border-r border-hairline p-6"><p className="font-mono text-xs text-copper">0{i+1}</p><h3 className="mt-3 text-lg">{area}</h3></article>)}</div></div></section>
<section className="border-b border-hairline"><div className="mx-auto grid w-full max-w-7xl min-w-0 grid-cols-1 gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2"><div><h2>What you receive</h2><ul className="mt-6 space-y-4 text-ink-secondary"><li>• A concise view of the material commercial issues found.</li><li>• A prioritised set of practical next actions.</li><li>• Clear boundaries between internal fixes and work that may need specialist support.</li><li>• A discussion of sensible next steps, without pressure to continue.</li></ul></div><div><h2>What we need from you</h2><p className="mt-6 text-ink-secondary">A working conversation and the relevant information already used to manage trading, stock, transport and finance. The exact request is agreed to suit the scope and available data.</p></div></div></section>
<section id="request" className="bg-panel"><div className="mx-auto grid w-full max-w-7xl min-w-0 grid-cols-1 gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-copper">Start here</p><h2 className="mt-3">Tell us what needs attention.</h2><p className="mt-4 text-ink-secondary">This short form helps us understand whether a Health Check is the right next step.</p></div><LeadForm source="health-check-page" /></div></section>
</>}