name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for VERCEL_TOKEN
        id: check_token
        run: |
          if [ -z "${{ secrets.VERCEL }}" ]; then
            echo "VERCEL secret is missing. Skipping deployment."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Install Vercel CLI
        if: steps.check_token.outputs.skip == 'false'
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        if: steps.check_token.outputs.skip == 'false'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL }}
      - name: Build Project Artifacts
        if: steps.check_token.outputs.skip == 'false'
        run: vercel build --prod --token=${{ secrets.VERCEL }}
      - name: Deploy Project Artifacts to Vercel
        if: steps.check_token.outputs.skip == 'false'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL }}
